### ISSUE TITLE
When the script hits ./configure says Importerror :No Module named numpy

### ISSUE THREAD

**Issue by harshasoftware** [jasonmayes/Tensor-Flow-on-Google-Compute-Engine#1]
`developersriharsha@tensorflow-1-instance-highcpu-4:~/Tensor-Flow-on-Google-Compute-Engine/tensorflow/tensorflow$` ./configure
Please specify the location of python. [Default is /usr/local/bin/python]: 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named numpy
ERROR: Problem getting numpy include path.  Is numpy installed?
developersriharsha@tensorflow-1-instance-highcpu-4:~/Tensor-Flow-on-Google-Compute-Engine/tensorflow/tensorflow$ `

**Comment by jasonmayes** [comment]
You should see just before you are asked to specify location in coloured text my message:

"Use /usr/bin/python for config and say NO to GPU support."

It will then work.
