### ISSUE TITLE
Python 3 option

### ISSUE THREAD

**Issue by waleedka** [jasonmayes/Tensor-Flow-on-Google-Compute-Engine#2]
Given that Tensforflow and all other libraries in this script support Python 3, it would be nice to update the script with a flag to use Python 3 instead.

**Comment by jasonmayes** [comment]
Noted. Thanks.

**Comment by jasonmayes** [comment]
If you alias python with the python version you want to use it should just use that. I have also updated the script to pull Python3 down.
